sonar.projectKey=helpdeskrshs_microservices_v6
sonar.projectName=helpdeskrshs_microservices_v6
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.login=sqp_880631bd92ed8dd3537f348d851b635dd8f39999
sonar.sources=app
sonar.tests=tests
sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.exclusions= \
    vendor/**/*, \
    storage/**/*, \
    bootstrap/cache/*, \
    public/**/*, \
    resources/views/**/*, \
    database/**/*, \
    config/**/*, \
    routes/**/*, \
    tests/**/*

sonar.sourceEncoding=UTF-8
