# Kunci unik untuk proyek Anda di SonarQube
sonar.projectKey=helpdeskrshs_microservices

# Nama proyek yang akan ditampilkan di dasbor SonarQube
sonar.projectName=helpdeskrshs_microservices

# Versi proyek
sonar.projectVersion=1.0

# Alamat server SonarQube Anda
sonar.host.url=http://localhost:9000

# Token otentikasi (lebih aman daripada username/password)
# Buat token di SonarQube: My Account > Security > Generate Tokens
sonar.login=sqp_718c3bc7262e3483e2cfb484cf454280b126be2b

# Direktori utama source code yang akan dianalisis
sonar.sources=app

# Direktori yang berisi file test
sonar.tests=tests

# Path ke laporan code coverage yang dihasilkan oleh PHPUnit
sonar.php.coverage.reportPaths=build/logs/clover.xml

# File dan direktori yang ingin dikecualikan dari analisis
sonar.exclusions= \
    vendor/**/*, \
    storage/**/*, \
    bootstrap/cache/*, \
    public/**/*, \
    resources/views/**/*, \
    database/**/*, \
    config/**/*, \
    routes/**/*, \
    tests/**/*

# Encoding file sumber
sonar.sourceEncoding=UTF-8
