sonar.projectKey=helpdeskrshs_microservices_v3
sonar.projectName=helpdeskrshs_microservices_v3
sonar.projectVersion=1.0
sonar.host.url=http://localhost:9000
sonar.login=sqp_f6fe047a78780d25468549cab349f966cfcb682a
sonar.sources=app
sonar.tests=tests
sonar.php.coverage.reportPaths=build/logs/clover.xml
sonar.exclusions= \
    vendor/**/*, \
    storage/**/*, \
    bootstrap/cache/*, \
    public/**/*, \
    resources/views/**/*, \
    database/**/*, \
    config/**/*, \
    routes/**/*, \
    tests/**/*

sonar.sourceEncoding=UTF-8
